### DISCUSSION TITLE
Vector Log Shipping: is there a way to use vectors transforms functionality  ?

### DISCUSSION THREAD

**Discussion by rueschm** [dokku/dokku#4303] [Q&A]
Hi,
thanks for fixing the reported bug about vector-logs so quickly. I try to use this integration to ship logs form the containers in Dokku  to Loki. My application running in Dokku produces unstructured logs and the log message is not parsed correctly.
In Vector I could use the `transforms` to address this problem. Is there a way I could use the `transforms` configuration between the sources and the sinks in combination with Dokku ? or is there an integration of this feature planned in the future ?

**Comment by josegonzalez** [comment]
There isn't a way at the moment because we write the entire config as is every time any sink is added or removed.

Would you mind writing how you think we should configure transforms? Would there be multiple transforms per sink?

**Reply by rueschm** [reply]
not easy to answer...it should probably be possible to define the sinks and the transforms on a global level, and then link the application either to a predefined sink directly or to a predefined transform, but how that could be achieved within the constraints of dokku, i do not know....

**Reply by josegonzalez** [reply]
Right. I guess I'm asking what sort of command interface would you want to use. Once we figure out how users will interact with dokku to add transforms, I can figure out how that would be structured internally.

**Comment by Otherguy123** [comment]
Came here looking for an answer to this, I'm very new to docker / dokku and don't fully understand it all yet, so apologies if this sounds dumb.

I was thinking you could have the vector-sink accept a filepath to the perpetual filesystem, in that filesystem you can create a transform file that holds all the goomph required, implement it something like `dokku logs:set <app_name> vector-sink "http://?uri=someurl.com:5341/api/events/raw&encoding=json&type=remap&source-uri=path/to/my/transform/file"` or URL.

Without knowing exactly what goes on to achieve this, other processes use something like `-v /var/lib/someapp/data:/data` to mount their perpetual data. Can the logs:set command access the apps connected storage ? If it can you could just buffer off of that and have users run something like `dokku storage:mount <app_name> /var/lib/dokku/data/storage/<app_name>/logsetup:/logsetup`, then have a standard filename of say transform.remap, that some other command would know to look for e.g. 
`dokku logs:set <app_name> vector-sink "http://?uri=someurl.com:5341/api/events/raw&encoding=json&type=remapfile"`
or
`dokku logs:set <app_name> vector-sink "http://?uri=someurl.com:5341/api/events/raw&encoding=json&type=remapfile" -v /var/lib/dokku/data/storage/<app_name>/logsetup:/logsetup`

I see the file being formatted the same way as previously required;

> . = parse_json!(.message)
.new_field = "new value"
.status = to_int!(.status)
.duration = parse_duration!(.duration, "s")
.new_name =   ##del(.old_name)

**Reply by fastidx** [reply]
Did you figure this out?

**Reply by jar-work** [reply]
coming late to the thread, but I solved this by adding sinks to save them in the host filesystem:

`dokku logs:set the-app vector-sink "file://?encoding[codec]=json&path=/var/log/dokku/apps/the-app-%25Y-%25m-%25d.log"`

after that, I just installed `vector` in the host to process the files, do the transformations to then send them to whatever any other sink I need . Example:

```
sources:
  logs_file:
    type: file
    include: ["/var/log/dokku/apps/*.log"]
    read_from: beginning

transforms:
  filter_out_modify:
    type: remap
    inputs: [logs_file]
    source: ". = parse_json!(.message, max_depth: 2)\ndel(.container_created_at)\ndel(.container_id)\ndel(.container_name)\ndel(.host)\ndel(.image)\n.name = get!(value: .label, path: [\"com.dokku.app-name\"])\ndel(.label)"

sinks:
  loki_fractal:
    type: loki
    inputs:
      - filter_out_modify
    endpoint: "....URL"
    encoding:
      codec: json
    labels:
      app: "{{name}}"
    auth:
      ....
```
it's not the ideal solution, but it gives me more flexibility to filter and transform the logs.
