### DISCUSSION TITLE
Docker instalation

### DISCUSSION THREAD

**Discussion by bralbral** [dokku/dokku#4534] [Q&A] [answered]
Good day! 

I tried to start using docker-compose.yml on windows10 :

```

version: '3'
services:

  dokku:
    image: dokku/dokku:latest
    container_name: dokku
    restart: unless-stopped
    #network_mode: host
    ports:
      - "3022:22"
      - "8080:80"
      - "8443:443"
    environment:
      DOKKU_HOSTNAME: bral
    volumes:
      - /var/lib/dokku:/mnt/dokku
      - /var/run/docker.sock:/var/run/docker.sock
```
After starting up:
![image](https://user-images.githubusercontent.com/54455457/112761186-be2ebb00-9002-11eb-8ffc-0d7e92ce4bf4.png)

But i cannot access to web localhost:8080 for continuation of instalation.

![image](https://user-images.githubusercontent.com/54455457/112761257-2aa9ba00-9003-11eb-9bf3-9da8353b1ea3.png)
