### DISCUSSION TITLE
Can`t get Flower with Django via dokku work, any help is appreciate

### DISCUSSION THREAD

**Discussion by henryfool91** [dokku/dokku#5080] [Q&A]
Hello everyone! I`m trying to run django + (redis+celery) + flower with dokku, but can't figure out, how to get it work, much appreciate any help, direction, anything! I tried to set proxy:ports-set http:5555:5555 ,  but i suppose it is not what i need - cause it sets 'web' to listen 5555, and not 'flower'

Can somebody point me where to dig? Thanks!

my procfile
```
web: gunicorn seo_service.wsgi:application
worker: celery -A seo_service worker -E -l debug
flower: celery -A seo_service flower -url_prefix=flower
````
my docker-compose
```
services:
 
  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.web
    command: /start.sh
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  redis:
    image: redis:alpine
    container_name: backend_rd
    expose:
      - 6379

  worker:
    build: .
    volumes:
      - .:/app
    command: celery -A seo_service worker -E -l debug
    container_name: backend_celery
    depends_on:
      - redis
      - web

  flower:
    build: ./
    command: celery -A seo_service flower
    links:
      - ""
    volumes:
      - .:/app
    ports:
      - 5555:5555
    expose:
      - 5555
    depends_on:
      - worker
      - redis

```
