### DISCUSSION TITLE
Can't push repo manually to server after using git:sync

### DISCUSSION THREAD

**Discussion by danielpetrica** [dokku/dokku#5247] [Q&A]
``Hi, I was trying to implent the github actions to deploy an app which i was previously deploying manually from the server with  
`dokku git:sync --build appname git@github.com:danielpetrica/---------.git main` 
But the actions returns an error at the end of the Push to dokku step. 

```
error: failed to push some refs to ' ssh://appname.com:22/appname
 ! [remote rejected] 7ba5ada927bd64fd490649f243b480ba5e67af35 -> main (branch is currently checked out)
To ssh://appname.com:22/appname
remote: 'receive.denyCurrentBranch' configuration variable to 'refuse'.        
remote: To squelch this message and still keep the default behaviour, set        
remote: 
remote: other way.        
remote: arranged to update its work tree to match what you pushed in some        
remote: its current branch; however, this is not recommended unless you        
remote: to 'ignore' or 'warn' in the remote repository to allow pushing into        
remote: You can set the 'receive.denyCurrentBranch' configuration variable        
remote: 
remote: the work tree to HEAD.        
remote: with what you pushed, and will require 'git reset --hard' to match        
remote: is denied, because it will make the index and work tree inconsistent        
remote: error: By default, updating the current branch in a non-bare repository        
remote: error: refusing to update checked out branch: refs/heads/main        
remote: 
remote:       [ https://appname.com](https://appname.com/)
remote:       [ http://appname.com](http://appname.com/)
remote: =====> Application deployed:    
remote: -----> Shutting down old containers in 60 seconds        
```

The application seems to still be built and doployed it just fails aftwewards. 
I've tried to do the push manually but got the same message. 
I've also tryied to use  the force flag but nothing changed `git_push_flags: '--force'` 

this is the workflow used : 

```
---
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
           branch: 'main'
           git_push_flags: '--force'
           git_remote_url: 'ssh://dokku@appname.com22/appname'
           ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
```
