### DISCUSSION TITLE
"subdomain.domain.com" is invalid. exiting...

### DISCUSSION THREAD

**Discussion by nemanjam** [dokku/dokku#5524] [Q&A] [answered]
I try to run Dokku container behind Traefik reverse proxy on `dokku.domain.com` subdomain. I pointed both `dokku.localhost3000.live` and `*.dokku.localhost3000.live` to server IP in Namecheap but Dokku container fails to boot with the following message:

```
*** Running /etc/my_init.d/10_dokku_init...,
-----> Cloning plugin repo https://github.com/dokku/dokku-postgres.git to /var/lib/dokku/plugins/available/postgres,
Cloning into 'postgres'...,
-----> Plugin postgres enabled,
 !     You haven't deployed any applications yet,
Adding user dokku to group adm,
-----> Priming bash-completion cache,
 !     "dokku.localhost3000.live" is invalid. exiting...,
*** /etc/my_init.d/10_dokku_init failed with status 1,
,
*** Killing all processes...
```

Here is my `docker-compose.yml`:

```yml
version: '3.8'

services:
  dokku:
    image: dokku/dokku:0.29.0
    container_name: dokku
    ports:
      - "3022:22"
      # - "8443:443"
      # - "8080:80"
    environment:
      - DOKKU_HOSTNAME="dokku.${DOMAIN}"
      - DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku
    volumes:
      - ./dokku-data:/mnt/dokku
      - /var/run/docker.sock:/var/run/docker.sock
      # - /var/lib/dokku:/mnt/dokku
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.dokku-https.rule=Host(`dokku.${DOMAIN}`)'
      - 'traefik.http.routers.dokku-https.entrypoints=websecure'
      - 'traefik.http.routers.dokku-https.service=dokku-svc'
      - 'traefik.http.services.dokku-svc.loadbalancer.server.port=80'

networks:
  proxy:
    external: true
```
Traefik is configured to redirect http to https, you can see it here:

https://github.com/nemanjam/traefik-proxy/blob/main/core/traefik-data/traefik.yml

Here is entire repo if you need more info:

https://github.com/nemanjam/traefik-proxy
