### DISCUSSION TITLE
GitHub Actions - Build Locally and Upload

### DISCUSSION THREAD

**Discussion by pn-wiseverge** [dokku/dokku#5602] [Q&A]
Hi.

I'm having some issues configuring the image upload to my dokku. The build is done on a GitHub Action and I want to upload the built image to my dokku, without uploading to any hub.

My Action is:

```
---
name: 'Deploy'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ vars.DOKKU_PROJECT_NAME }}:${{ github.sha }}

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_remote_url: 'ssh://dokku@${{ vars.DOKKU_IP }}:22/${{ vars.DOKKU_PROJECT_NAME }}'
          ssh_private_key: ${{ secrets.DOKKU_DEPLOYMENT_KEY }}
          deploy_docker_image: ${{ vars.DOKKU_PROJECT_NAME }}:${{ github.sha }}

```

I get this error during `Push to dokku`:

```
Deploying image to Dokku Host
-----> Generating build context
       Setting Dockerfile
-----> Pulling image
Error response from daemon: pull access denied for <project-name>, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
