### DISCUSSION TITLE
Passthrough all Dokku apps through existing Traefik proxy

### DISCUSSION THREAD

**Discussion by nemanjam** [dokku/dokku#5701] [Q&A] [answered]
I already have Traefik and Portainer on my server and want to add Dokku to its subdomain `dokku.arm1.localhost3002.live` so that apps go passthrough Traefik like `app1.dokku.arm1.localhost3002.live` without hardcoding each app in Traefik. Idea is that Traefik handles `portainer.arm1.localhost3002.live` and that Dokku handles all `*.dokku.arm1.localhost3002.live`.

I can't bind both Traefik and Dokku to 80 and 443 ports at same time. Traefik is also Docker container attached to `proxy` network.

I did this, but i see this is wrong because Dokku container exposes apps directly to the host and not to the Dokku container.

```bash
ubuntu@arm1:~/traefik-proxy/apps/dokku$ docker exec -it dokku bash dokku proxy:ports nextjs-blank-dokku
-----> Port mappings for nextjs-blank-dokku
    -----> scheme  host port  container port
    http           80         5000
```

```yaml
version: '3.8'

services:
  dokku:
    container_name: dokku
    # image: dokku/dokku:0.30.1
    build:
      context: .
      # install pack in Dockerfile
      dockerfile: Dockerfile
    ports:
      - '3022:22'
      # - '8443:443'
      # - '8080:80'
    environment:
      - DOKKU_HOSTNAME=dokku.${SERVER_HOSTNAME}
      - DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku
    volumes:
      - ./dokku-data:/mnt/dokku
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      # traefik will handle letsencrypt
      - 'traefik.http.routers.dokku-http.rule=HostRegexp(`{subdomain:[[:ascii:]]+}.dokku.${SERVER_HOSTNAME}`)'
      - 'traefik.http.routers.dokku-http.entrypoints=web'
      # dokku default exposes 80 and 443
      - 'traefik.http.services.dokku-http.loadbalancer.server.port=80'
      # passthrough https
      - 'traefik.tcp.routers.dokku-https.tls=true'
      - 'traefik.tcp.routers.dokku-https.tls.passthrough=true'
      - 'traefik.tcp.routers.dokku-https.rule=HostSNIRegexp(`{subdomain:[[:ascii:]]+}.dokku.${SERVER_HOSTNAME}`)'
      - 'traefik.tcp.routers.dokku-https.entrypoints=websecure'
      - 'traefik.tcp.services.dokku-https.loadbalancer.server.port=443'

networks:
  proxy:
    external: true

```

How can I use networks or proxy features to passthrough all http and https from all Dokku apps through existing Traefik router?
