### DISCUSSION TITLE
Anyone succeed with rootless docker?

### DISCUSSION THREAD

**Discussion by gardner** [dokku/dokku#7298] [Q&A]
Docker has been configured in rootless mode.

I am using a docker compose file:

```
services:
  dokku:
    image: dokku/dokku:0.35.6
    container_name: dokku
    ports:
      - "3022:22"
      - "8080:80"
      - "8443:443"
    volumes:
      - "$PWD/var/lib/dokku:/mnt/dokku"
      - "/run/user/1000/docker.sock:/var/run/docker.sock"
    environment:
      DOKKU_HOSTNAME: dokku.me
      DOKKU_HOST_ROOT: "$PWD/var/lib/dokku/home/dokku"
      DOKKU_LIB_HOST_ROOT: "$PWD/var/lib/dokku/var/lib/dokku"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token $CF_TOKEN
    depends_on:
      - dokku
```

When I push the rails example to Dokku:

```
git push dokku main
Enumerating objects: 585, done.
Counting objects: 100% (585/585), done.
Delta compression using up to 8 threads
Compressing objects: 100% (280/280), done.
Writing objects: 100% (585/585), 142.00 KiB | 71.00 MiB/s, done.
Total 585 (delta 275), reused 582 (delta 273), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (275/275), done.
-----> Set main as deploy-branch
-----> Cleaning up...
-----> Building ruby-getting-started from herokuish
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
remote: Error response from daemon: Cannot link to a non running container: /dokku.postgres.railsdatabase AS /determined_solomon/dokku-postgres-railsdatabase
remote: Error: failed to start containers: 7f025260cc03e605c420cdff81003cc857366bffe606887621ecb5db82ac96ee
remote: You cannot attach to a stopped container, start it first
remote:  !     Failure during app build
remote:  !     Removing invalid image tag dokku/ruby-getting-started:latest
remote:  !     App build failed
```

Relevant:

`Linux 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux`

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

```
$ docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:11 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:11 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.3.1
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /run/user/1000/dockerd-rootless
 slirp4netns:
  Version:          1.2.0
  GitCommit:        656041d45cfca7a4176f6b7eed9e4fe6c11e8383
```
