### DISCUSSION TITLE
How to get Dokku deploys to work using a Tailscale IP address via GitHub Actions?

### DISCUSSION THREAD

**Discussion by bakatz** [dokku/dokku#7464] [Q&A] [answered]
I'm not sure if this is the right place for this kind of question or if the issue I filed is in the right place, so x-posting it here: https://github.com/dokku/github-action/issues/96

Has anyone tried to get this kind of setup to work before? Would appreciate any insights as I've already spent a couple hours banging my head against the wall trying to get this to work. Thanks!

**Comment by bakatz** [comment, marked as answer]
Answering my own question: the usual Dokku GitHub Actions step is not compatible with Tailscale because it  assumes "sshcommand" will run commands upon a new ssh session being started. Unfortunately, sshcommand works with `authorized_keys` which Tailscale completely bypasses due to the way it works.

As a workaround, just run Dokku commands manually. You will need to:
1. Initialize Tailscale at the top of your actions file and make sure SSH keyscan runs:
```
    - name: Set up Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
        tags: tag:ci

    - name: Initialize SSH Known Hosts
      run: |
        mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
        ssh-keyscan -T 30 ${{ env.DOKKU_HOST }} >> ~/.ssh/known_hosts
```

2. Execute any Dokku commands such as deploys yourself instead of using the GitHub action and make sure to prepend "dokku" to all commands since sshcommand is being skipped:
```
    - name: Deploy API
      run: ssh dokku@${{ env.DOKKU_HOST }} -- dokku git:from-image "your-app" "ghcr.io/your-app:${{ github.sha }}"

    - name: Run Some Job
      run: ssh dokku@${{ env.DOKKU_HOST }} -- dokku run your-app ./app run_job something
```
