### ISSUE TITLE
Linking Apps and exposing URL

### ISSUE THREAD

**Issue by chgad** [dokku/dokku#3296]
Hello everyone, i have a Question about "linking Dokku apps" i could yet not find anything wich allows this.  The only built-in mechanics is the linking of databases.
## Description of problem

I'm working with docker-compose locally with the following `docker-compose.yml` :
```
version: '3'

services:
  db:
    environment:
      POSTGRES_DB: db_app
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    restart: always
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.web
    command: /start.sh
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  rabbit_broker:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=broker_adm
      - RABBITMQ_DEFAULT_PASS=mbroker_pass
    ports:
      - "5673:5672"

  celery_worker:
    build:
      context: .
        dockerfile: ./docker/local/Dockerfile.celery
      volumes:
        - .:/app
      links:
        - rabbit_broker
      depends_on:
        - rabbit_broker
```

Now i want to make this work on Dokku on our servers (Implementation with only web and db works in our process). Those new created containers `rabbit_broker` and `celery_broker` should become Dokku apps but need to be linked to eachother and the `rabbit_broker` should expose an URL (like the DATABASE_URL for databases) to acces it within the main app (in local: web).

How can I achieve such linking within Dokku ?

Note: I have found the plugin/function `docker-options` but i'm unsure about if this is the right way to go.

I apriciate every comment on this topic, thanks in advance
