### ISSUE TITLE
dokku-installer assumes the existence of "python", which isn't always true

### ISSUE THREAD

**Issue by palfrey** [dokku/dokku#3714]
## Description of problem

```
    default: Setting up dokku-installer
    default: /usr/bin/env:
    default: ‘python’
    default: : No such file or directory
    default: dpkg: error processing package dokku (--configure):
    default:
    default:  subprocess installed post-installation script returned error exit status 127
```

### How reproducible

Every time

### Steps to Reproduce

1. Install Dokku on a fresh Ubuntu Xenial machine with python 3 installed but not python 2

#### Actual Results

Failure to run dokku-installer

## Environment Information

Version: 0.19.1

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Debian package from Packagecloud, in Virtualbox

Note that "python3" exists as a command here, but not "python"
