### ISSUE TITLE
option for redirect to https with traefik

### ISSUE THREAD

**Issue by caplod** [dokku/dokku#5858]
### Description of feature

if you use traefik as a proxy and have letsencrypt enabled, there is no redirect to https.

it would be great to have an option for that. 
maybe global or per app basis.

**Comment by josegonzalez** [comment]
This shouldn't be the case as we inject the following global rules:

```

      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
```

I wonder if force-adding the http routes on apps allows the http routes to work standalone?

**Comment by caplod** [comment]
yes I see the same with `dokku traefik:show-config`  but there is no redirect from http to https.

can you confirm its working?

**Comment by josegonzalez** [comment]
@caplod if you're still running this locally, do you mind editing your template to do the above and see if it works as expected after stopping/starting traefik?

**Comment by caplod** [comment]
my `/var/lib/dokku/core-plugins/available/traefik-vhosts/templates/compose.yml.sigil`looks like this and the redirect to https  is working fine.

```
---
version: "3.7"

services:
  traefik:
    image: "{{ $.TRAEFIK_IMAGE }}"
    command:
      - --entrypoints.http.address=:80
      {{ if $.TRAEFIK_LETSENCRYPT_EMAIL }}
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443

      {{ end }}
      - --providers.docker
      - --api={{ $.TRAEFIK_API_ENABLED }}
      - --api.dashboard={{ $.TRAEFIK_DASHBOARD_ENABLED }}

      - --log.level={{ $.TRAEFIK_LOG_LEVEL }}
      - --log.format=json

      {{ if $.TRAEFIK_LETSENCRYPT_EMAIL }}
      - --certificatesresolvers.leresolver.acme.caserver={{ $.TRAEFIK_LETSENCRYPT_SERVER }}
      - --certificatesresolvers.leresolver.acme.email={{ $.TRAEFIK_LETSENCRYPT_EMAIL }}
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
      {{ end }}

    labels:
      {{ if $.TRAEFIK_API_ENABLED }}
      # Dashboard
      - "traefik.http.routers.api.rule=Host(`{{ $.TRAEFIK_API_VHOST }}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints={{ if $.TRAEFIK_LETSENCRYPT_EMAIL }}https{{ else }}http{{ end }}"
      {{ end }}
      
      - "traefik.http.routers.api.middlewares=auth"
      {{ if $.TRAEFIK_BASIC_AUTH }}
      - "traefik.http.middlewares.auth.basicauth.users={{ $.TRAEFIK_BASIC_AUTH }}"
      {{ end }}

      {{ if $.TRAEFIK_LETSENCRYPT_EMAIL }}
      - "traefik.http.routers.api.tls.certresolver=leresolver"
      {{ end }}

    network_mode: bridge

    ports:
      - "80:80"
      {{ if $.TRAEFIK_LETSENCRYPT_EMAIL }}
      - "443:443"
      {{ end }}

    restart: unless-stopped

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ $.TRAEFIK_DATA_DIR }}/traefik-acme.json:/acme.json"
```
