### ISSUE TITLE
Cannot start vagrant on Windows

### ISSUE THREAD

**Issue by Cactusbone** [dokku/dokku#7155]
### Description of problem

I've tried following [dokku/docs/getting-started/install/vagrant.md at master · dokku/dokku](https://github.com/dokku/dokku/blob/master/docs/getting-started/install/vagrant.md)

So I installed virtualbox 7.0 (7.1 is not accepted by Vagrant), and vagrant 2.4.1.

Running `env BOX_MEMORY=2048 vagrant up dokku-windows --provider=virtualbox` seems to work (when using master, switching to any branch fails), up to the following error:

```
    dokku-windows: apt-get update -qq
    dokku-windows: make: jq: Command not found
    dokku-windows: wget -qO /usr/local/bin/docker-image-labeler
    dokku-windows: wget: missing URL
    dokku-windows: Usage: wget [OPTION]... [URL]...
    dokku-windows:
    dokku-windows: Try `wget --help' for more options.
    dokku-windows: make: *** [Makefile:156: docker-image-labeler] Error 1
```

It seems jq is used in Makefile before it's available.

I believe it should be first in dependencies rule, or it should be a dependency of docker-image-labeler

### Steps to reproduce

Follow [[dokku/docs/getting-started/install/vagrant.md at master · dokku/dokku](https://github.com/dokku/dokku/blob/master/docs/getting-started/install/vagrant.md)](https://github.com/dokku/dokku/blob/master/docs/getting-started/install/vagrant.md) on a Windows host

### dokku report $APP_NAME

not available
